import Footer from './Components/Footer'
import Navber from './Components/Navber'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Manage',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navber />
        {children}
        <Footer />
        </body>
    </html>
  )
}
